version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php82Learn
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html
    build: 
      context: .
      dockerfile: dockerfile
  db:
    image: mysql:8.0
    container_name: mysql8
    command: default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD : pass
      MYSQL_DATABASE : demo
      MYSQL_USER : test
      MYSQL_PASSWORD : pass
    ports:
      - 3307:3306


    